### Динпрога 3

Субподрядчик Деда Мороза получил отрез ткани $n \times m$ сантиметров. Ему известно, что из куска ткани $a_i \times b_i$ можно сшить изделие стоимостью $c_i$, всего разных типов изделий $n$. Разрезать ткань можно только прямолинейными разрезами в целых координатах. Дорезать до половины и повернуть ножницы нельзя. Помогите субподрядчику найти оптимальную последовательность разрезов и максимальную стоимость изделий, которые можно изготовить из отреза ткани.

In [19]:
# complexity:
# n * m * (n + m - 2)
# if m = \Theta(n) then O(n^3)

import numpy as np

height, width = 12, 14
A = [2, 4, 3]
B = [3, 6, 1]
C = [5, 12, 2]

# height, width = 4, 5
# A = [1, 1]
# B = [2, 3]
# C = [3, 4]

cost = np.zeros((height + 1, width + 1))

for a, b, c in zip(A, B, C):
    cost[a, b] = c
    #cost[b, a] = c

#print(cost)

for row in range(1, height + 1):
    for col in range(1, width + 1):
        #print(f"{row=}, {col=}:")
        
        # all possible horizontal cuts
        for cut_ind in range(1, row // 2 + 1):
            #print("horiz cut")
            curr_cost = cost[cut_ind, col] + cost[row - cut_ind, col]
            cost[row, col] = max(cost[row, col], curr_cost)

        # all possible vertical cuts
        for cut_ind in range(1, col // 2 + 1):
            #print(f"vert cut {cut_ind=}")
            curr_cost = cost[row, cut_ind] + cost[row, col - cut_ind]
            #print("possible update: ", curr_cost)
            cost[row, col] = max(cost[row, col], curr_cost)
        
        #print(cost[row, col])
        #print()
    
    #break

print(cost[1 : , 1 :])


[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   5.   5.   5.  10.  10.  10.  15.  15.  15.  20.  20.  20.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.  28.]
 [  2.   4.  10.  12.  14.  20.  22.  24.  30.  32.  34.  40.  42.  44.]
 [  2.   4.  11.  13.  15.  22.  24.  26.  33.  35.  37.  44.  46.  48.]
 [  4.   8.  15.  19.  23.  30.  34.  38.  45.  49.  53.  60.  64.  68.]
 [  4.   8.  16.  20.  24.  32.  36.  40.  48.  52.  56.  64.  68.  72.]
 [  4.   8.  20.  24.  28.  40.  44.  48.  60.  64.  68.  80.  84.  88.]
 [  6.  12.  21.  27.  33.  42.  48.  54.  63.  69.  75.  84.  90.  96.]
 [  6.  12.  25.  31.  37.  50.  56.  62.  75.  81.  87. 100. 106. 112.]
 [  6.  12.  26.  32.  38.  52.  58.  64.  78.  84.  90. 104. 110. 116.]
 [  8.  16.  30.  38.  46.  60.  68.  76.  90.  98. 106. 120. 128. 136.]]
